"use client";

import { useEffect, useState, useRef } from "react";
import { useParams, useSearchParams, useRouter } from "next/navigation";
import {
  CheckCircle,
  Download,
  Home,
  Loader2,
  FileText,
  Users,
  Clock,
  ListChecks,
  Lightbulb,
  MessageSquare,
  AlertCircle,
} from "lucide-react";

interface ActionItem {
  item: string;
  assignee: string;
  due_date: string;
}

interface MeetingSummaryData {
  success: boolean;
  message: string;
  room_id: string;
  meeting_data: {
    room_id: string;
    participant_name: string;
    start_time: string;
    end_time: string | null;
    duration_seconds: number;
    duration_formatted: string;
    participants: string[];
    transcript_count: number;
    summary: string | null;
    minutes: Record<string, unknown> | null;
  };
  summary: string;
  minutes: {
    meeting_date: string;
    duration: string;
    participants: string[];
    summary: string;
    key_points: string[];
    action_items: ActionItem[];
    decisions: string[];
    topics_discussed: string[];
  };
  key_points: string[];
  action_items: ActionItem[];
  decisions: string[];
  topics_discussed: string[];
}

export default function MeetingEndPage() {
  const params = useParams();
  const searchParams = useSearchParams();
  const router = useRouter();
  const roomId = params.roomId as string;
  const userName = searchParams.get("name") || "Guest";

  const [summaryData, setSummaryData] = useState<MeetingSummaryData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const fetchSummary = async () => {
      try {
        const pythonApiUrl =
          typeof window !== "undefined" &&
          (process.env.NEXT_PUBLIC_PYTHON_API_URL || "").trim() === ""
            ? window.location.origin
            : process.env.NEXT_PUBLIC_PYTHON_API_URL || "http://localhost:5000";

        const response = await fetch(`${pythonApiUrl}/api/meeting/end`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            room_id: roomId,
            participant_name: userName,
          }),
        });

        if (!response.ok) {
          throw new Error(`Server responded with ${response.status}`);
        }

        const data: MeetingSummaryData = await response.json();
        setSummaryData(data);
      } catch (err) {
        console.error("Error fetching meeting summary:", err);
        setError(
          err instanceof Error ? err.message : "Failed to generate meeting summary."
        );
      } finally {
        setIsLoading(false);
      }
    };

    fetchSummary();
  }, [roomId, userName]);

  const handleDownloadPDF = () => {
    if (!printRef.current) return;

    const printContents = printRef.current.innerHTML;
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Meeting Minutes - ${roomId}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; }
          .header { text-align: center; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #e0e0e0; }
          .header h1 { font-size: 24px; color: #1a1a2e; margin-bottom: 4px; }
          .header p { font-size: 13px; color: #666; }
          .meta { display: flex; gap: 32px; margin-bottom: 28px; padding: 16px; background: #f8f9fa; border-radius: 8px; }
          .meta-item { font-size: 13px; }
          .meta-item strong { display: block; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #888; margin-bottom: 2px; }
          .section { margin-bottom: 24px; }
          .section h2 { font-size: 16px; color: #1a1a2e; margin-bottom: 10px; padding-bottom: 6px; border-bottom: 1px solid #eee; }
          .section p { font-size: 14px; color: #333; }
          .section ul { padding-left: 20px; }
          .section li { font-size: 14px; color: #333; margin-bottom: 6px; }
          .action-table { width: 100%; border-collapse: collapse; font-size: 13px; }
          .action-table th, .action-table td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
          .action-table th { background: #f0f0f0; font-weight: 600; }
          .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #aaa; border-top: 1px solid #eee; padding-top: 16px; }
        </style>
      </head>
      <body>
        ${printContents}
        <div class="footer">Generated by Orbicall AI Meeting Assistant</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 400);
  };

  const hasMeaningfulSummary =
    summaryData &&
    summaryData.summary &&
    summaryData.summary !== "No transcript was recorded during this meeting." &&
    summaryData.summary !== "No transcript available for summary.";

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Thank You Hero */}
      <div className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-600/20 via-purple-600/10 to-transparent" />
        <div className="relative max-w-4xl mx-auto px-6 pt-16 pb-10 text-center">
          <div className="w-20 h-20 mx-auto mb-6 bg-gradient-to-br from-emerald-400 to-green-500 rounded-full flex items-center justify-center shadow-lg shadow-emerald-500/30">
            <CheckCircle className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-4xl font-bold mb-3 bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent">
            Thank You for Joining!
          </h1>
          <p className="text-gray-400 text-lg max-w-md mx-auto">
            Your meeting <span className="text-indigo-400 font-medium">{roomId}</span> has
            ended. Here is your AI-generated meeting summary.
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 pb-20">
        {/* Loading State */}
        {isLoading && (
          <div className="flex flex-col items-center justify-center py-24">
            <Loader2 className="w-12 h-12 text-indigo-400 animate-spin mb-6" />
            <h2 className="text-xl font-semibold text-gray-200 mb-2">
              Generating Meeting Summary...
            </h2>
            <p className="text-gray-500 text-sm">
              Our AI is analyzing your meeting transcript with GPT-4o
            </p>
          </div>
        )}

        {/* Error State */}
        {error && !isLoading && (
          <div className="bg-red-900/20 border border-red-500/30 rounded-2xl p-8 text-center">
            <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
            <h2 className="text-xl font-semibold text-red-300 mb-2">
              Could not generate summary
            </h2>
            <p className="text-red-400/80 text-sm mb-6">{error}</p>
            <button
              onClick={() => router.push("/")}
              className="px-6 py-3 bg-gray-800 text-white rounded-xl hover:bg-gray-700 transition-colors"
            >
              Return to Home
            </button>
          </div>
        )}

        {/* Summary Content */}
        {summaryData && !isLoading && (
          <>
            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3 mb-8 justify-center">
              {hasMeaningfulSummary && (
                <button
                  onClick={handleDownloadPDF}
                  className="flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-xl hover:bg-indigo-700 transition-colors shadow-lg shadow-indigo-600/20"
                >
                  <Download className="w-5 h-5" />
                  Download Minutes as PDF
                </button>
              )}
              <button
                onClick={() => router.push("/")}
                className="flex items-center gap-2 px-6 py-3 bg-gray-800 text-gray-200 rounded-xl hover:bg-gray-700 transition-colors border border-gray-700"
              >
                <Home className="w-5 h-5" />
                Return to Home
              </button>
            </div>

            {/* Meeting Meta */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
              <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center gap-3">
                <div className="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
                  <Clock className="w-5 h-5 text-blue-400" />
                </div>
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wide">Duration</p>
                  <p className="text-sm font-medium text-gray-200">
                    {summaryData.meeting_data?.duration_formatted || summaryData.minutes?.duration || "N/A"}
                  </p>
                </div>
              </div>
              <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center gap-3">
                <div className="w-10 h-10 bg-purple-500/20 rounded-lg flex items-center justify-center">
                  <Users className="w-5 h-5 text-purple-400" />
                </div>
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wide">Participants</p>
                  <p className="text-sm font-medium text-gray-200">
                    {summaryData.minutes?.participants?.join(", ") ||
                      summaryData.meeting_data?.participants?.join(", ") ||
                      userName}
                  </p>
                </div>
              </div>
              <div className="bg-gray-900 border border-gray-800 rounded-xl p-4 flex items-center gap-3">
                <div className="w-10 h-10 bg-amber-500/20 rounded-lg flex items-center justify-center">
                  <FileText className="w-5 h-5 text-amber-400" />
                </div>
                <div>
                  <p className="text-xs text-gray-500 uppercase tracking-wide">Date</p>
                  <p className="text-sm font-medium text-gray-200">
                    {summaryData.minutes?.meeting_date || new Date().toLocaleDateString()}
                  </p>
                </div>
              </div>
            </div>

            {/* Summary Section */}
            <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 mb-6">
              <div className="flex items-center gap-2 mb-4">
                <MessageSquare className="w-5 h-5 text-indigo-400" />
                <h2 className="text-lg font-semibold text-white">Meeting Summary</h2>
              </div>
              <p className="text-gray-300 leading-relaxed whitespace-pre-wrap">
                {summaryData.summary || "No summary available."}
              </p>
            </div>

            {/* Key Points */}
            {summaryData.key_points && summaryData.key_points.length > 0 && (
              <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <Lightbulb className="w-5 h-5 text-amber-400" />
                  <h2 className="text-lg font-semibold text-white">Key Points</h2>
                </div>
                <ul className="space-y-2">
                  {summaryData.key_points.map((point, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <span className="mt-1.5 w-2 h-2 rounded-full bg-amber-400 shrink-0" />
                      <span className="text-gray-300 text-sm">{point}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Action Items */}
            {summaryData.action_items && summaryData.action_items.length > 0 && (
              <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <ListChecks className="w-5 h-5 text-emerald-400" />
                  <h2 className="text-lg font-semibold text-white">Action Items</h2>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-gray-700">
                        <th className="text-left py-2 px-3 text-gray-400 font-medium">Action</th>
                        <th className="text-left py-2 px-3 text-gray-400 font-medium">Assignee</th>
                        <th className="text-left py-2 px-3 text-gray-400 font-medium">Due Date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {summaryData.action_items.map((action, i) => (
                        <tr key={i} className="border-b border-gray-800 last:border-0">
                          <td className="py-3 px-3 text-gray-300">
                            {typeof action === "string" ? action : action.item}
                          </td>
                          <td className="py-3 px-3 text-gray-400">
                            {typeof action === "string" ? "—" : action.assignee || "—"}
                          </td>
                          <td className="py-3 px-3 text-gray-400">
                            {typeof action === "string" ? "—" : action.due_date || "TBD"}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Decisions */}
            {summaryData.decisions && summaryData.decisions.length > 0 && (
              <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <CheckCircle className="w-5 h-5 text-blue-400" />
                  <h2 className="text-lg font-semibold text-white">Decisions Made</h2>
                </div>
                <ul className="space-y-2">
                  {summaryData.decisions.map((decision, i) => (
                    <li key={i} className="flex items-start gap-3">
                      <span className="mt-1.5 w-2 h-2 rounded-full bg-blue-400 shrink-0" />
                      <span className="text-gray-300 text-sm">{decision}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Topics Discussed */}
            {summaryData.topics_discussed && summaryData.topics_discussed.length > 0 && (
              <div className="bg-gray-900 border border-gray-800 rounded-2xl p-6 mb-6">
                <div className="flex items-center gap-2 mb-4">
                  <FileText className="w-5 h-5 text-purple-400" />
                  <h2 className="text-lg font-semibold text-white">Topics Discussed</h2>
                </div>
                <div className="flex flex-wrap gap-2">
                  {summaryData.topics_discussed.map((topic, i) => (
                    <span
                      key={i}
                      className="px-3 py-1.5 bg-purple-500/10 border border-purple-500/30 rounded-lg text-sm text-purple-300"
                    >
                      {topic}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </>
        )}
      </div>

      {/* Hidden printable content for PDF */}
      {summaryData && hasMeaningfulSummary && (
        <div className="hidden">
          <div ref={printRef}>
            <div className="header">
              <h1>Minutes of Meeting</h1>
              <p>Room: {roomId}</p>
            </div>

            <div className="meta">
              <div className="meta-item">
                <strong>Date</strong>
                {summaryData.minutes?.meeting_date || new Date().toLocaleDateString()}
              </div>
              <div className="meta-item">
                <strong>Duration</strong>
                {summaryData.meeting_data?.duration_formatted || summaryData.minutes?.duration || "N/A"}
              </div>
              <div className="meta-item">
                <strong>Participants</strong>
                {summaryData.minutes?.participants?.join(", ") || userName}
              </div>
            </div>

            <div className="section">
              <h2>Summary</h2>
              <p>{summaryData.summary}</p>
            </div>

            {summaryData.key_points && summaryData.key_points.length > 0 && (
              <div className="section">
                <h2>Key Points</h2>
                <ul>
                  {summaryData.key_points.map((point, i) => (
                    <li key={i}>{point}</li>
                  ))}
                </ul>
              </div>
            )}

            {summaryData.action_items && summaryData.action_items.length > 0 && (
              <div className="section">
                <h2>Action Items</h2>
                <table className="action-table">
                  <thead>
                    <tr>
                      <th>Action</th>
                      <th>Assignee</th>
                      <th>Due Date</th>
                    </tr>
                  </thead>
                  <tbody>
                    {summaryData.action_items.map((action, i) => (
                      <tr key={i}>
                        <td>{typeof action === "string" ? action : action.item}</td>
                        <td>{typeof action === "string" ? "—" : action.assignee || "—"}</td>
                        <td>{typeof action === "string" ? "—" : action.due_date || "TBD"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {summaryData.decisions && summaryData.decisions.length > 0 && (
              <div className="section">
                <h2>Decisions Made</h2>
                <ul>
                  {summaryData.decisions.map((decision, i) => (
                    <li key={i}>{decision}</li>
                  ))}
                </ul>
              </div>
            )}

            {summaryData.topics_discussed && summaryData.topics_discussed.length > 0 && (
              <div className="section">
                <h2>Topics Discussed</h2>
                <ul>
                  {summaryData.topics_discussed.map((topic, i) => (
                    <li key={i}>{topic}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
